name: my
channels:
  - nlesc
dependencies:
  - python=2.7
  - nomkl
  - matplotlib=1.5.1
  - numpy=1.10.4
  - scipy=0.17.0
  - pandas=0.17.1
  - scikit-learn=0.17.1
  - six=1.10.0
  - cython==0.25.2
  - pip:
    - ipykernel==4.3.1
    - notebook==4.2.1
    - astropy==1.3.2
    - theano==0.8.2
    - xgboost==0.4a30
    - fastFM==0.2.9
